import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Gridmaps.",
  description: "Generated by create next app",
  icons: {
    icon: [
      { url: '/GridMaps_Icon_Pack/04_Web_Favicons/favicon-16x16.png', sizes: '16x16', type: 'image/png' },
      { url: '/GridMaps_Icon_Pack/04_Web_Favicons/favicon-32x32.png', sizes: '32x32', type: 'image/png' },
      { url: '/GridMaps_Icon_Pack/04_Web_Favicons/favicon.ico' },
    ],
    apple: [
      { url: '/GridMaps_Icon_Pack/04_Web_Favicons/apple-touch-icon-180x180.png', sizes: '180x180', type: 'image/png' },
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased dark scroll-smooth`}
    >
      <body className={`${geistSans.className} min-h-full flex flex-col bg-zinc-950 text-zinc-50`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
